# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Signup_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from .signupSuccess import Ui_signup_message_dialog


class Ui_signup_dialog(QtWidgets.QDialog):
    def __init__(self, login_page):
        self.login_page = login_page
        super().__init__()
        signup_dialog = self
        self.setupUi(signup_dialog)

    def setupUi(self, signup_dialog):
        signup_dialog.setObjectName("signup_dialog")
        signup_dialog.resize(527, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(signup_dialog.sizePolicy().hasHeightForWidth())
        signup_dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../Desktop/logo.356db89e.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signup_dialog.setWindowIcon(icon)
        signup_dialog.setSizeGripEnabled(False)
        signup_dialog.setModal(False)
        self.frame = QtWidgets.QFrame(signup_dialog)
        self.frame.setGeometry(QtCore.QRect(0, 10, 527, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo_image = QtWidgets.QLabel(self.frame)
        self.logo_image.setText("")
        self.logo_image.setPixmap(QtGui.QPixmap(".\\../Desktop/logo.356db89e.png"))
        self.logo_image.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_image.setObjectName("logo_image")
        self.verticalLayout.addWidget(self.logo_image)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Cayload_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Cayload_label.setFont(font)
        self.Cayload_label.setObjectName("Cayload_label")
        self.verticalLayout.addWidget(self.Cayload_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.logisticService_lable = QtWidgets.QLabel(self.frame)
        self.logisticService_lable.setObjectName("logisticService_lable")
        self.verticalLayout.addWidget(self.logisticService_lable)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.username_label = QtWidgets.QLabel(self.frame)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout_3.addWidget(self.username_label)
        self.username_box = QtWidgets.QLineEdit(self.frame)
        self.username_box.setObjectName("username_box")
        self.horizontalLayout_3.addWidget(self.username_box)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.password_label = QtWidgets.QLabel(self.frame)
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_4.addWidget(self.password_label)
        self.password_box = QtWidgets.QLineEdit(self.frame)
        self.password_box.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_box.setObjectName("password_box")
        self.horizontalLayout_4.addWidget(self.password_box)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.signup_button = QtWidgets.QPushButton(signup_dialog)
        self.signup_button.setGeometry(QtCore.QRect(10, 540, 503, 28))
        self.signup_button.setObjectName("signup_button")

        self.retranslateUi(signup_dialog)
        self.signup_button.clicked.connect(self.signup)
        QtCore.QMetaObject.connectSlotsByName(signup_dialog)

    def retranslateUi(self, signup_dialog):
        _translate = QtCore.QCoreApplication.translate
        signup_dialog.setWindowTitle(_translate("signup_dialog", "Blockchain Framework"))
        self.Cayload_label.setText(_translate("signup_dialog", "<html><head/><body><p align=\"center\">Blockchain Framework</p></body></html>"))
        self.logisticService_lable.setText(_translate("signup_dialog", "<html><head/><body><p align=\"center\">Sign-Up Page</p></body></html>"))
        self.username_label.setText(_translate("signup_dialog", "username :"))
        self.password_label.setText(_translate("signup_dialog", "password :"))
        self.label.setText(_translate("signup_dialog", "Company Name :"))
        self.signup_button.setText(_translate("signup_dialog", "Sign Up"))

    def signup(self):
        username = str(self.username_box.text()).strip().replace("\n", "")
        password = str(self.password_box.text())
        site_name = str(self.lineEdit.text())

        url = "http://127.0.0.1:8000/site/"
        json_data = {
            "siteName" : site_name,
            "adminUsername" : username,
            "adminPassword" : password
        }

        req = requests.post(
            url=url,
            json=json_data
        )
        if req.status_code == 201:
            self.close()
            self.signup_success = Ui_signup_message_dialog(self.login_page)
            self.signup_success.show()
        else:
            print("There is a problem")
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signup_dialog = QtWidgets.QDialog()
    ui = Ui_signup_dialog()
    ui.setupUi(signup_dialog)
    signup_dialog.show()
    sys.exit(app.exec_())
