# Generated by Django 4.1 on 2022-09-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default=None, max_length=200, null=True, unique=True)),
                ('data', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('url', models.CharField(default=None, max_length=200)),
                ('data', models.CharField(default=None, max_length=1000)),
                ('created_on', models.CharField(default=None, max_length=200)),
                ('user_info', models.CharField(default=None, max_length=200)),
                ('contract_info', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('adminUsername', models.CharField(default='admin', max_length=50)),
                ('adminPassword', models.CharField(default='admin', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SiteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.service')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.login')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.site', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteBlockhain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.blockchian')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.site', unique=True)),
            ],
        ),
    ]
