# Generated by Django 4.1.3 on 2022-11-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='params',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
