# Generated by Django 4.1.3 on 2022-11-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_service_params_alter_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchian',
            name='site_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
